In [1]:
import numpy as ny
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset=pd.read_csv('insurance_pre.csv')
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)
indepen=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
depen=dataset[['charges']]
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(indepen,depen,test_size=1/3,random_state=0)

In [3]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [4]:
scy=StandardScaler()
y_train=scy.fit_transform(y_train)
y_test=scy.transform(y_test)

In [8]:
import pickle
filename="finalized_model_DR.sav"

In [9]:
preinput_data=[[25,33.5,3,1,0]]

In [10]:
preinput=sc.transform(preinput_data)
preinput

C:\Anaconda\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[-1.03919296,  0.45834558,  1.58903774,  1.01127431, -0.49929923]])

In [11]:
load_model=pickle.load(open("finalized_model_DR.sav",'rb'))
result=load_model.predict(preinput)
result

array([-0.72113791])

In [12]:
preoutput=scy.inverse_transform([result])
preoutput

array([[4618.0799]])